site_name: Catedra UCM-ONCE 
site_url: https://catedraonce.github.io
markdown_extensions:
    - admonition
nav:
        - Inicio: index.md
        - Proyectos:
               - InnoVision: Projects/InnoVision.md
               - IrisEmp: Projects/IrisEmp.md
               - DACTYLS: Projects/Dactyls.md  
        - Novedades: News/index.md
        - Formación: Formacion/Formacion.md
        - Empleo: Empleo/index.md
        - Premios Cátedra: Premios/index.md                
        - Conferencias: Conferencias/index.md
        - Contacto: Contact/index.md