site_name: Catedra UCM-ONCE 
site_url: https://catedraonce.github.io
markdown_extensions:
    - admonition
nav:
        - Inicio: index.md
        - Novedades: News/index.md
        - Empleo: Empleo/index.md
        - Premios Cátedra: Premios/index.md
        - Módulos:
                - Módulo 1: Subjects/Modulo1/index.md
                - Módulo 2: Subjects/Modulo2/index.md
                - Módulo 3: Subjects/Modulo3/index.md
                - Módulo 4: Subjects/Modulo4/index.md
                
        - Contacto: Contact/index.md